using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using MwsLib.DB.SqlServer.PcSafetySupport;
using DataGridViewAutoFilter;
using MwsLib.BaseFactory.PcSafetySupport;

namespace PcSafetySupport.Forms
{
	/// <summary>
	/// PC安心サポート管理情報登録画面
	/// </summary>
	public partial class PcSupportControlListForm : Form
	{
		/// <summary>
		/// PC安心サポート管理情報リスト
		/// </summary>
		private List<PcSupportControl> PcSupportControlList;

		/// <summary>
		/// デフォルトコンストラクタ
		/// </summary>
		public PcSupportControlListForm()
		{
			InitializeComponent();

			PcSupportControlList = null;
			dataGridViewControl.BindingContextChanged += new EventHandler(dataGridViewControl_BindingContextChanged);
		}

		/// <summary>
		/// Form Load
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void PcSupportControlListForm_Load(object sender, EventArgs e)
		{
			dataGridViewControl.DataSource = null;
			dataGridViewControl.Rows.Clear();
			dataGridViewControl.Columns.Clear();
			dataGridViewControl.ReadOnly = true;

			DataTable dataTable = PcSafetySupportAccess.GetPcSupportControl("", true);
			BindingSource dataSource = new BindingSource(dataTable, null);
			dataGridViewControl.DataSource = dataSource;

			// カラム名の変更
			dataGridViewControl.Columns["CUSTOMER_ID"].HeaderText = "顧客ID";
			dataGridViewControl.Columns["GOODS_ID"].HeaderText = "商品ID";
			dataGridViewControl.Columns["START_DATE"].HeaderText = "契約開始日";
			dataGridViewControl.Columns["END_DATE"].HeaderText = "契約終了日";
			dataGridViewControl.Columns["PERIOD_END_DATE"].HeaderText = "利用期限日";
			dataGridViewControl.Columns["AGREE_YEAR"].HeaderText = "契約年数";
			dataGridViewControl.Columns["PRICE"].HeaderText = "料金";
			dataGridViewControl.Columns["MARKETING_SPECIALIST_ID"].HeaderText = "営業担当者ID";
			dataGridViewControl.Columns["BRANCH_ID"].HeaderText = "支店ID";
			dataGridViewControl.Columns["APPLY_DATE"].HeaderText = "申込日付";
			dataGridViewControl.Columns["APPLY_REPORT_ACCEPT"].HeaderText = "申込用紙有無";
			dataGridViewControl.Columns["MALE_ADDRESS"].HeaderText = "メールアドレス";
			dataGridViewControl.Columns["REMARK1"].HeaderText = "備考１";
			dataGridViewControl.Columns["REMARK2"].HeaderText = "備考２";
			dataGridViewControl.Columns["START_MALE_DATE"].HeaderText = "開始メール送信日時";
			dataGridViewControl.Columns["GUIDE_MALE_DATE"].HeaderText = "契約更新案内メール送信日時";
			dataGridViewControl.Columns["UPDATE_MALE_DATE"].HeaderText = "契約更新メール送信日時";
			dataGridViewControl.Columns["CANCEL_DATE"].HeaderText = "解約日時";
			dataGridViewControl.Columns["CANCEL_REPORT_ACCEPT"].HeaderText = "解約届有無";
			dataGridViewControl.Columns["CANCEL_REASON"].HeaderText = "解約事由";
			dataGridViewControl.Columns["CREATE_DATE"].HeaderText = "作成日時";
			dataGridViewControl.Columns["CREATE_PERSON"].HeaderText = "作成者";
			dataGridViewControl.Columns["UPDATE_DATE"].HeaderText = "更新日時";
			dataGridViewControl.Columns["UPDATE_PERSON"].HeaderText = "更新者";
			dataGridViewControl.Columns["WW_RENEWAL_FLAG"].HeaderText = "WonderWeb更新フラグ";

			dataGridViewControl.ResumeLayout();

			PcSupportControlList = PcSafetySupportController.ConvertPcSupportControl(dataTable);
		}

		/// <summary>
		/// Configures the autogenerated columns, replacing their header
		/// cells with AutoFilter header cells. 
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void dataGridViewControl_BindingContextChanged(object sender, EventArgs e)
		{
			// Continue only if the data source has been set.
			if (dataGridViewControl.DataSource == null)
			{
				return;
			}
			// Add the AutoFilter header cell to each column.
			foreach (DataGridViewColumn col in dataGridViewControl.Columns)
			{
				col.HeaderCell = new DataGridViewAutoFilterColumnHeaderCell(col.HeaderCell);
			}
			// Resize the columns to fit their contents.
			//dataGridViewUser.AutoResizeColumns();
		}

		private void textBoxCustomerID_TextChanged(object sender, EventArgs e)
		{
			if (8 == textBoxCustomerID.Text.Length)
			{
				PcSupportControl control = PcSupportControlList.Find(p => p.CustomerID == textBoxCustomerID.Text);
				if (null != control)
				{
					// 変更
					using (PcSupportControlForm form = new PcSupportControlForm(control))
					{
						if (DialogResult.OK == form.ShowDialog())
						{
							DataTable dataTable = PcSafetySupportAccess.GetPcSupportControl("", true);
							BindingSource dataSource = new BindingSource(dataTable, null);
							dataGridViewControl.DataSource = dataSource;
						}
					}
				}
				else
				{
					// 追加
					using (PcSupportControlForm form = new PcSupportControlForm(textBoxCustomerID.Text))
					{
						if (DialogResult.OK == form.ShowDialog())
						{
							DataTable dataTable = PcSafetySupportAccess.GetPcSupportControl("", true);
							BindingSource dataSource = new BindingSource(dataTable, null);
							dataGridViewControl.DataSource = dataSource;
						}
					}
				}
			}
		}

		private void dataGridViewControl_MouseDoubleClick(object sender, MouseEventArgs e)
		{
			int customerID = (int)dataGridViewControl.CurrentRow.Cells[0].Value;
			PcSupportControl control = PcSupportControlList.Find(p => p.CustomerID == customerID.ToString());
			if (null != control)
			{
				// 変更
				using (PcSupportControlForm form = new PcSupportControlForm(control))
				{
					if (DialogResult.OK == form.ShowDialog())
					{
						DataTable dataTable = PcSafetySupportAccess.GetPcSupportControl("", true);
						BindingSource dataSource = new BindingSource(dataTable, null);
						dataGridViewControl.DataSource = dataSource;
					}
				}
			}
		}
	}
}
