SELECT  M_SERVICE.SERVICE_ID             AS ServiceCode
      , M_SERVICE.[SERVICE_NAME]         AS ServiceName
	  , M_SERVICE.PARENTS_SERVICE_ID     AS ParentSrviceCode
      , M_SERVICE_TYPE.SERVICE_TYPE_ID   AS ServiceType
      , M_SERVICE_TYPE.SERVICE_TYPE_NAME AS ServiceTypeName
      , V_PCA_GOODS.PRICE                AS Price
      , M_CODE.GOODS_ID                  AS GoodID
      , V_PCA_GOODS.GOODS_NAME           AS GoodsName
      , V_PCA_GOODS.BRAND_CLASSIFICATION AS GoodsKubun
FROM           dbo.M_SERVICE       M_SERVICE
    INNER JOIN dbo.M_SERVICE_TYPE  M_SERVICE_TYPE ON (M_SERVICE.SERVICE_TYPE_ID = M_SERVICE_TYPE.SERVICE_TYPE_ID)
    INNER JOIN dbo.M_CODE          M_CODE         ON (M_SERVICE.SERVICE_ID      = M_CODE.SERVICE_ID)
    INNER JOIN dbo.V_PCA_GOODS     V_PCA_GOODS    ON (M_CODE.GOODS_ID           = V_PCA_GOODS.GOODS_ID)
    --LEFT  JOIN dbo.M_CODE          ValuePack      ON (M_SERVICE.SERVICE_ID      = ValuePack.SERVICE_ID
    --                                                 and (ValuePack.GOODS_ID = '800101' or ValuePack.GOODS_ID ='800104'))
WHERE  (M_SERVICE.DELETE_FLG = N'0') AND (M_SERVICE.UMU_FLG = N'0') AND (M_CODE.DELETE_FLG = N'0') AND (M_CODE.SET_SALE = 1)
		AND (M_SERVICE.SERVICE_ID <> '1099')
		and (V_PCA_GOODS.BRAND_CLASSIFICATION = 200 or V_PCA_GOODS.BRAND_CLASSIFICATION = 201 or V_PCA_GOODS.BRAND_CLASSIFICATION = 211 or V_PCA_GOODS.BRAND_CLASSIFICATION = 212 or V_PCA_GOODS.BRAND_CLASSIFICATION = 214)
		ORDER BY M_SERVICE.SERVICE_ID ASC