USE [charlieDB]
GO

/****** Object:  Table [dbo].[T_USE_CLOUDDATA_LICENSE]    Script Date: 2020/10/02 12:08:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_USE_CLOUDDATA_LICENSE](
	[fLisenceId] [varchar](50) NOT NULL,
	[fCpID] [nvarchar](11) NULL,
	[fUmuFlg] [varchar](1) NULL,
	[fUpdateDate] [datetime] NULL,
 CONSTRAINT [PK_T_USE_CLOUDDATA_LICENSE] PRIMARY KEY CLUSTERED 
(
	[fLisenceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

