using DataGridViewAutoFilter;
using MwsLib.BaseFactory.EntryFinishedUser;
using MwsLib.DB.SqlServer.EntryFinishedUser;
using System;
using System.Collections.Generic;
using System.Data;
using System.Windows.Forms;

namespace EntryFinishedUser
{
	/// <summary>
	/// リスト参照画面
	/// </summary>
	public partial class ShowListForm : Form
	{
		/// <summary>
		/// リスト参照データ
		/// </summary>
		public List<EntryFinishedUserData> UserList { get; set; }

		/// <summary>
		/// デフォルトコンストラクタ
		/// </summary>
		public ShowListForm()
		{
			InitializeComponent();

			dataGridViewUser.BindingContextChanged += new EventHandler(dataGridViewUser_BindingContextChanged);
			//dataGridViewUser.KeyDown += new KeyEventHandler(dataGridViewUser_KeyDown);
			//dataGridViewUser.DataBindingComplete += new DataGridViewBindingCompleteEventHandler(dataGridViewUser_DataBindingComplete);
		}

		/// <summary>
		/// コンストラクタ
		/// </summary>
		/// <param name="list">リスト参照データ</param>
		public ShowListForm(List<EntryFinishedUserData> list)
		{
			InitializeComponent();

			UserList = list;

			dataGridViewUser.BindingContextChanged += new EventHandler(dataGridViewUser_BindingContextChanged);
			//dataGridViewUser.KeyDown += new KeyEventHandler(dataGridViewUser_KeyDown);
			//dataGridViewUser.DataBindingComplete += new DataGridViewBindingCompleteEventHandler(dataGridViewUser_DataBindingComplete);
		}

		/// <summary>
		/// Form Load
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void ShowListForm_Load(object sender, EventArgs e)
		{
			dataGridViewUser.DataSource = null;
			dataGridViewUser.Rows.Clear();
			dataGridViewUser.Columns.Clear();
			dataGridViewUser.ReadOnly = true;

			DataTable table = EntryFinishedUserDataGetIO.GetEntryFinishedUserDataList(Program.DATABACE_ACCEPT_CT);
			BindingSource dataSource = new BindingSource(table, null);
			dataGridViewUser.DataSource = dataSource;

			//dataGridViewUser.DataSource = UserList;
			//string[] title = EntryFinishedUserData.ToTitleArray();
			//for (int i = 0; i < title.Length; i++)
			//{
			//	dataGridViewUser.Columns[i].HeaderText = title[i];
			//}
			//// 終了届受領日を非表示
			//dataGridViewUser.Columns[title.Length].Visible = false;

			// 終了届受領日を非表示
			dataGridViewUser.Columns[16].Visible = false;
			dataGridViewUser.ResumeLayout();
		}

		/// <summary>
		/// Configures the autogenerated columns, replacing their header
		/// cells with AutoFilter header cells. 
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void dataGridViewUser_BindingContextChanged(object sender, EventArgs e)
		{
			// Continue only if the data source has been set.
			if (dataGridViewUser.DataSource == null)
			{
				return;
			}
			// Add the AutoFilter header cell to each column.
			foreach (DataGridViewColumn col in dataGridViewUser.Columns)
			{
				col.HeaderCell = new DataGridViewAutoFilterColumnHeaderCell(col.HeaderCell);
			}
			// Resize the columns to fit their contents.
			//dataGridViewUser.AutoResizeColumns();
		}

		//// Displays the drop-down list when the user presses 
		//// ALT+DOWN ARROW or ALT+UP ARROW.
		//private void dataGridViewUser_KeyDown(object sender, KeyEventArgs e)
		//{
		//	if (e.Alt && (e.KeyCode == Keys.Down || e.KeyCode == Keys.Up))
		//	{
		//		DataGridViewAutoFilterColumnHeaderCell filterCell = dataGridViewUser.CurrentCell.OwningColumn.HeaderCell as DataGridViewAutoFilterColumnHeaderCell;
		//		if (filterCell != null)
		//		{
		//			filterCell.ShowDropDownList();
		//			e.Handled = true;
		//		}
		//	}
		//}
	}
}
