USE [charlieDB]
GO

/****** Object:  Table [dbo].[T_USE_CLOUDDATA_LICENSE_ERROR_USER]    Script Date: 2020/10/05 16:37:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_USE_CLOUDDATA_LICENSE_ERROR_USER](
	[fCustomerID] [int] NOT NULL,
	[fUpdateDate] [datetime] NULL,
	[fUpdatePerson] [nvarchar](30) NULL,
 CONSTRAINT [PK_T_USE_CLOUDDATA_LICENSE_ERROR_USER] PRIMARY KEY CLUSTERED 
(
	[fCustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

