USE [charlieDB]
GO

/****** Object:  Table [dbo].[T_PC_SUPPORT_MAIL]    Script Date: 2018/11/13 9:29:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_PC_SUPPORT_MAIL](
	[MAIL_NO] [int] IDENTITY(1,1) NOT NULL,
	[ORDER_NO] [nvarchar](8) NULL,
	[CUSTOMER_ID] [int] NULL,
	[SEND_MAIL_TYPE] [nvarchar](1) NULL,
	[GOODS_ID] [nvarchar](13) NULL,
	[PRICE] [int] NULL,
	[AGREE_YEAR] [int] NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[BRANCH_ID] [nvarchar](10) NULL,
	[SALESMAN_ID] [nvarchar](4) NULL,
	[ORDER_DATE] [datetime] NULL,
	[MAIL_ADDRESS] [nvarchar](50) NULL,
	[SEND_DATE] [datetime] NULL,
 CONSTRAINT [PK_T_PC_SUPPORT_MALE] PRIMARY KEY CLUSTERED 
(
	[MAIL_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[T_PC_SUPPORT_MAIL] ADD  CONSTRAINT [DF_T_PC_SUPPORT_MALE_CUSTOMER_ID]  DEFAULT ((0)) FOR [CUSTOMER_ID]
GO

ALTER TABLE [dbo].[T_PC_SUPPORT_MAIL] ADD  CONSTRAINT [DF_T_PC_SUPPORT_MALE_MALE_TYPE]  DEFAULT ((0)) FOR [SEND_MAIL_TYPE]
GO

ALTER TABLE [dbo].[T_PC_SUPPORT_MAIL] ADD  CONSTRAINT [DF_T_PC_SUPPORT_MALE_PRICE]  DEFAULT ((0)) FOR [PRICE]
GO

ALTER TABLE [dbo].[T_PC_SUPPORT_MAIL] ADD  CONSTRAINT [DF_T_PC_SUPPORT_MALE_AGREE_YEAR]  DEFAULT ((0)) FOR [AGREE_YEAR]
GO

