USE [charlieDB]
GO

/****** Object:  Table [dbo].[T_PC_SUPPORT_CONTROL]    Script Date: 2018/11/13 9:29:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_PC_SUPPORT_CONTROL](
	[ORDER_NO] [nvarchar](8) NOT NULL,
	[CUSTOMER_ID] [int] NULL,
	[CLINIC_NAME] [nvarchar](80) NULL,
	[GOODS_ID] [nvarchar](13) NULL,
	[GOODS_NAME] [nvarchar](50) NULL,
	[PRICE] [int] NULL,
	[AGREE_YEAR] [int] NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[PERIOD_END_DATE] [datetime] NULL,
	[BRANCH_ID] [nvarchar](10) NULL,
	[BRANCH_NAME] [nvarchar](30) NULL,
	[SALESMAN_ID] [nvarchar](4) NULL,
	[SALESMAN_NAME] [nvarchar](20) NULL,
	[ORDER_DATE] [datetime] NULL,
	[ORDER_REPORT_ACCEPT] [nvarchar](1) NULL,
	[ORDER_APPROVAL_DATE] [datetime] NULL,
	[MAIL_ADDRESS] [nvarchar](50) NULL,
	[REMARK] [nvarchar](512) NULL,
	[START_MAIL_DATE] [datetime] NULL,
	[GUIDE_MAIL_DATE] [datetime] NULL,
	[UPDATE_MAIL_DATE] [datetime] NULL,
	[CANCEL_DATE] [datetime] NULL,
	[CANCEL_REPORT_ACCEPT] [nvarchar](1) NULL,
	[CANCEL_REASON] [nvarchar](500) NULL,
	[DISABLE_FLAG] [nvarchar](1) NULL,
	[WW_RENEWAL_FLAG] [nvarchar](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_PERSON] [nvarchar](20) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_PERSON] [nvarchar](20) NULL,
 CONSTRAINT [PK_T_PC_SUPPORT_CONTROL] PRIMARY KEY CLUSTERED 
(
	[ORDER_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[T_PC_SUPPORT_CONTROL] ADD  CONSTRAINT [DF_T_PC_SUPPORT_CONTROL_CUSTOMER_ID]  DEFAULT ((0)) FOR [CUSTOMER_ID]
GO

ALTER TABLE [dbo].[T_PC_SUPPORT_CONTROL] ADD  CONSTRAINT [DF_T_PC_SUPPORT_CONTROL_PRICE]  DEFAULT ((0)) FOR [PRICE]
GO

ALTER TABLE [dbo].[T_PC_SUPPORT_CONTROL] ADD  CONSTRAINT [DF_T_PC_SUPPORT_CONTROL_AGREE_YEAR]  DEFAULT ((0)) FOR [AGREE_YEAR]
GO

ALTER TABLE [dbo].[T_PC_SUPPORT_CONTROL] ADD  CONSTRAINT [DF_T_PC_SUPPORT_CONTROL_ORDER_REPORT_ACCEPT]  DEFAULT ((0)) FOR [ORDER_REPORT_ACCEPT]
GO

ALTER TABLE [dbo].[T_PC_SUPPORT_CONTROL] ADD  CONSTRAINT [DF_T_PC_SUPPORT_CONTROL_WW_RENEWAL_FLAG]  DEFAULT ((0)) FOR [WW_RENEWAL_FLAG]
GO

